In [1]:
print ("hello world")

hello world


In [2]:
#感觉这些东西的套路，都是前向传播吨吨吨填，矩阵能算明白就行
import tensorflow as tf
import input_data
mnist=input_data.read_data_sets("MNIST_data/",one_hot=True)

F:\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [22]:
print (mnist)

<input_data.read_data_sets.<locals>.DataSets object at 0x000001A26BCB73C8>


In [23]:
print (mnist.train)

In [24]:
print (mnist.train.images)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
print (mnist.train.images[0])
print (mnist.train.images[0].size)

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

In [26]:
print (mnist.train.labels)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [27]:
print (mnist.train.labels[0])
print (mnist.train.labels[0].size)

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
10


In [42]:
x=tf.placeholder("float",[None,784])   #这个东西是占位用的，先说这个东西长什么样，然后过一阵再填
W=tf.Variable(tf.zeros([784,10]))
b=tf.Variable(tf.zeros([10]))
y=tf.nn.softmax(tf.matmul(x,W)+b)
y_=tf.placeholder("float",[None,10])    #这个东西也是占位用的
cross_entropy=-tf.reduce_sum(y_*tf.log(y))   #最开始交叉熵公式里，y_和y都是放在log里面的，但是0和1这种，log里不行啊。然后这个是简化一点点的交叉熵。
train_step=tf.train.GradientDescentOptimizer(0.01).minimize(cross_entropy)   #以0.01的学习速率最小化交叉熵
init=tf.initialize_all_variables()
sess=tf.Session()
sess.run(init)
for i in range(1000):
    batch_xs,batch_ys=mnist.train.next_batch(100)
    sess.run(train_step,feed_dict={x:batch_xs,y_:batch_ys})

In [43]:
correct_prediction=tf.equal(tf.argmax(y,1),tf.argmax(y_,1))
accuracy=tf.reduce_mean(tf.cast(correct_prediction,"float"))
print (sess.run(accuracy,feed_dict={x:mnist.test.images,y_:mnist.test.labels}))
sess.close()

0.9132
